# !/usr/bin/env python3
# Generated by Proteus Visual Designer for Raspberry Pi

# Modules
import var
import pio
import cpu
import Ports
from time import sleep

def peripheral_setup () :
 pio.cpu=cpu.CPU ()
 pio.uart=Ports.UART ()

def verificacion():
 for i in range(len(var.nomina)):
  if var.Name == var.nomina[i]:
   pio.uart.println ("Hello "+var.nomina[i])
   sleep(0.2)
   pio.uart.print ("Whats your password? ")
   var.passw = pio.uart.input (True)
   sleep(0.2)
   if var.passw == var.clave[i]:
    pio.uart.println ("Welcome to ESPOL ")
   else:
    pio.uart.println ("passw incorrecta ")
   return
   sleep(0.2)
 
def variables_setup () :
 var.Name = ''
 var.nomina = ["tonny","andrea","laura","andres"]
 var.clave = ["1234","2345","3456","4567"]
def chart_SETUP () :
 pio.uart.setup(115200)
 pio.uart.print ("Whats your name? ")
 var.Name = pio.uart.input (True)
 verificacion()
 sleep(0.3)
 return

# Main function
def main () :
# Setup
 variables_setup ()
 peripheral_setup ()
# Infinite loop
 while True :
  chart_SETUP ()
  pass
# Command line execution
if __name__ == '__main__' :
   main()
