# !/usr/bin/env python3
# Generated by Proteus Visual Designer for Raspberry Pi

# Modules
from time import sleep
from wiringpi import Serial

baud = 115200
ser  = Serial("/dev/serial0",baud)
sleep(0.3)
nomina = ["tonny","alisson","christopher","victor"]
clave = ["1234","2345","3456","4567"]

def verificacion(Name):
 for i in range(len(nomina)):
  if Name == nomina[i]:
   printsln ("Hello "+ nomina[i])
   sleep(0.2)
   prints ("Whats your password? ")
   passw = recibir ()
   sleep(0.2)
   if passw == clave[i]:
    printsln ("Welcome to ESPOL ")
   else:
    printsln ("passw incorrecta ")
   return
   sleep(0.2)

def recibir(echo = True):
 data = ""
 while True:
  input = ser.getchar()
  if echo:
   ser.putchar(input)
  if input == "\r":
   return (data)
  data += input
 sleep(0.2)
  
def printsln(menss):
 ser.puts(menss+"\r")
 sleep(0.2)

def prints(menss):
 ser.puts(menss)
 sleep(0.2)

# Main function
def main () :

# Infinite loop
 while True :
  prints("hola como te llamas? ")
  mensaje = recibir()
  verificacion(mensaje)
  pass

# Command line execution
if __name__ == '__main__' :
   main()

