# !/usr/bin/env python3
# Generated by Proteus Visual Designer for Raspberry Pi

# Modules
import var
import pio
import cpu
import Ports
from time import sleep

def peripheral_setup () :
 pio.cpu=cpu.CPU ()
 pio.uart=Ports.UART ()

def variables_setup () :
 var.Name = ''

def chart_SETUP () :
 pio.uart.setup(115200)
 pio.uart.print ("Whats your name? ")
 var.Name = pio.uart.input (True)
 pio.uart.println ("Hello "+var.Name)
 sleep(0.2)
 return

# Main function
def main () :
# Setup
 variables_setup ()
 peripheral_setup ()
# Infinite loop
 while True :
  chart_SETUP ()
  pass
# Command line execution
if __name__ == '__main__' :
   main()
