# !/usr/bin/env python3
# Generated by Proteus Visual Designer for Raspberry Pi

# Modules
from time import sleep
from wiringpi import Serial

baud = 115200
ser  = Serial("/dev/serial0",baud)
sleep(0.3)

def recibir(echo = True):
 data = ""
 while True:
  input = ser.getchar()
  if echo:
   ser.putchar(input)
  if input == "\r":
   return (data)
  data += input
 sleep(0.2)
  
def printsln(menss):
 ser.puts(menss+"\r")
 sleep(0.2)

def prints(menss):
 ser.puts(menss)
 sleep(0.2)

# Main function
def main () :

# Infinite loop
 while True :
  prints("hola como te llamas? ")
  mensaje = recibir()
  printsln("Bienvenido "+mensaje)
  pass

# Command line execution
if __name__ == '__main__' :
   main()

